// <auto-generated />
namespace EntityTest_19_12_2023.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class aith : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aith));
        
        string IMigrationMetadata.Id
        {
            get { return "202401081331156_aith"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
